---
printWidth: 100
tabWidth: 4
useTabs: true
trailingComma: none
semi: true
singleQuote: true
overrides:
    - files: '*.md'
      options:
          tabWidth: 2
    - files: '*.svelte'
      options:
          parser: svelte
plugins:
    - prettier-plugin-organize-imports
    - prettier-plugin-svelte
    - prettier-plugin-tailwindcss
